name: Go Build

permissions:
  "contents": "write"

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            output: bonbon-reminder
          - os: macos-latest
            output: bonbon-reminder
          - os: windows-latest
            output: bonbon-reminder.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
      - name: Build
        run: go build -o ${{ matrix.output }} .
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: bonbon-reminder-${{ matrix.os }}
          path: ${{ matrix.output }}
  build-helpers:
    name: Build Helpers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            suffix: ""
          - os: macos-latest
            suffix: ""
          - os: windows-latest
            suffix: ".exe"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
      - name: Build
        run: |
          mkdir compiled
          go build -o compiled/get-account-access-${{ matrix.os }}${{ matrix.suffix }} cmd/get-account-access.go
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: helpers-${{ matrix.os }}
          path: compiled
  create-release:
    needs: [build, build-helpers]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@v6
        name: Checkout Code

      - uses: actions/download-artifact@v8
        name: Download Windows
        with:
          name: bonbon-reminder-windows-latest
          path: release-artifacts/

      - name: Rename Windows Binary
        run: mv release-artifacts/bonbon-reminder.exe release-artifacts/bonbon-reminder-Windows.exe

      - uses: actions/download-artifact@v8
        name: Download Linux
        with:
          name: bonbon-reminder-ubuntu-latest
          path: release-artifacts/

      - name: Rename Linux Binary
        run: mv release-artifacts/bonbon-reminder release-artifacts/bonbon-reminder-Linux

      - uses: actions/download-artifact@v8
        name: Download Mac
        with:
          name: bonbon-reminder-macos-latest
          path: release-artifacts/

      - name: Rename Mac Binary
        run: mv release-artifacts/bonbon-reminder release-artifacts/bonbon-reminder-Mac

      - uses: actions/download-artifact@v8
        name: Download Windows Helper
        with:
          name: helpers-windows-latest
          path: release-artifacts/

      - uses: actions/download-artifact@v8
        name: Download Linux Helper
        with:
          name: helpers-ubuntu-latest
          path: release-artifacts/

      - uses: actions/download-artifact@v8
        name: Download Mac Helper
        with:
          name: helpers-macos-latest
          path: release-artifacts/

      - name: Create release
        uses: ncipollo/release-action@v1.21.0
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "release-artifacts/*"
          body: ${{ github.event.head_commit.message }}
          prerelease: true
          name: Nightly Release
          tag: nightly-build

      - name: Update nightly-build tag
        run: |
          git tag -f nightly-build
          git push -f origin nightly-build
        shell: bash
