name: Go Build

permissions:
  "contents": "write"

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            output: Bonbon-Reminder-Linux
          - os: macos-latest
            output: Bonbon-Reminder-Mac
          - os: windows-latest
            output: Bonbon-Reminder-Windows.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
      - name: Build
        run: go build -o ${{ matrix.output }} .
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bonbon-Reminder-${{ matrix.os }}
          path: ${{ matrix.output }}
  build-helpers:
    name: Build Helpers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            output: get-account-access-Linux
          - os: macos-latest
            output: get-account-access-Mac
          - os: windows-latest
            output: get-account-access-Windows.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
      - name: Build
        run: |
          mkdir compiled
          go build -o compiled/${{ matrix.output }} cmd/get-account-access.go
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: helpers-${{ matrix.os }}
          path: compiled
  create-release:
    needs: [build, build-helpers]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@v6
        name: Checkout Code

      - uses: actions/download-artifact@v8
        name: Download artifacts
        with:
          path: release-artifacts/
          merge-multiple: true

      - name: Create release
        uses: ncipollo/release-action@v1.21.0
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "release-artifacts/*"
          body: ${{ github.event.head_commit.message }}
          prerelease: true
          name: Nightly Release
          tag: nightly-build

      - name: Update nightly-build tag
        run: |
          git tag -f nightly-build
          git push -f origin nightly-build
        shell: bash
